//  Common ENUM

export const CommonMaster = {
 GENERAL_MASTER : 'General Masters',
 PRICE : 'Price',
 METAL_MASTER : 'Metal Masters',
 METAL_WEIGHT : 'Metal Weight',
 COLOR_STONE : 'Color Stone',
 LABOUR_CHARGE : 'Labour Charge',
 CAREER_MASTER : 'Career Masters',
 CAREER_DESIGNATION : 'Career Designation',
 CAREER_LOCATION : 'Career Location',
 DIAMOND_MASTER : 'Diamond Masters',
 DIAMOND_QUALITY : 'Diamond Quality',
 CAREER_REFERENCE : 'Career Reference',
 DIAMOND_CLARITIES : 'Diamond Clarities',
 DIAMOND_COLOR : 'Diamond Color',
 DIAMOND_SHAPES : 'Diamond Shapes',
 DIAMOND_SIEVES : 'Diamond Sieves',
 LENGTH : 'Length',
 GAUGE : 'Gauge',
 SHOP_MODULES : 'Shop For Module',
 PRODUCT_CERTIFICATES : 'Product Certificates',
 RETURN_REASONS : 'Return Reasons',
 SOLITAIR_MASTER : 'Solitaire Masters',
 SOLITAIR_COLOR : 'Solitaire Color',
 SOLITAIR_CUT : 'Solitaire Cut',
 SOLITAIR_CLARITY : 'Solitaire Clarity',
 SOLITAIR_SHAPE : 'Solitaire Shape',
 SOLITAIR_POLISH : 'Solitaire Polish',
 SOLITAIR_SYMMETRY : 'Solitaire Symmetry',
 SOLITAIR_LABS : 'Solitaire Labs',
 SOLITAIR_EYE_CLEAN : 'Solitaire Eye Cleans',
 OCCASION : 'Occasion',
 BANGLE_SIZE : 'Bangle Size',
 BANGLE_BRACELATE : 'Bangle Bracelate',
 PRODUCT_WEAR_TAG : 'Product Wear Tag',
 METAL_PURITY : 'Metal Purity',
 GENDER : 'Gender',
 PRODUCT_LOOKS_TAG : 'Product Looks Tag',
 METAL_TYPE : 'Metal Type',
 FAQ : 'FAQ',
 CMS : 'CMS',
 EVENT : 'Event',
 COUPON : 'Coupon',
 GROUP_MASTER : 'Group Master',
 CONTACT_US : 'Contact Us',
 BLOG : 'Blogs',
 TESTIMONIAL : 'Testimonial',
 SUBSCRIBE : 'Subscribe',
 REQUESTS : 'Requests',
 SYSTEM_EMAIL : 'System Emails',
 RINGSIZE: 'Ring Size',
 PRODUCT_MASTER :'Product Master',
 BANGLE_MASTER: 'Bangle Master',
 SOCIAL:'Social',
 OUR_CLIENTS:'Our Clients',
 OUR_BENEFITS:'Our Benefits',
 DOWNLOAD_OUR_APP: 'Download Our App',
 CUSTOMIZE_JEWELLERY:'Customize Your jewellery',
 DIGITAL_STORE:'Digital Store',
 GENERAL_CONFIGURATION:'General Configuration',
 SETTING:'Setting',
 CONTACTADDRESS:'Contact Addresses',
 CATEGORY_MANAGEMENT:'Category Management',
 FILTER_SEQUENCE : 'Filter Sequence',
 ACCOUNT : 'Account',
 BANNER : 'Banner'
}
